export const SIGNUP_BEGINS = 'SIGNUP_BEGINS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const LOGIN_BEGINS = 'LOGIN_BEGINS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_EXPENSE_TITLE = 'ADD_EXPENSE_TITLE';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';

export const SAVE_EXPENSE_BEGINS = 'SAVE_EXPENSE_BEGINS';
export const SAVE_EXPENSE_SUCCESS = 'SAVE_EXPENSE_SUCCESS';
export const SAVE_EXPENSE_FAIL = 'SAVE_EXPENSE_FAIL';

export const GET_EXPENSES_BEGINS = 'GET_EXPENSES_BEGINS';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const GET_EXPENSES_FAIL = 'GET_EXPENSES_FAIL';
